### ISSUE TITLE
WebGL Renderer

### ISSUE THREAD

**Issue by hunterloftis** [hunterloftis/newton#1]
The examples tend to be render-limited rather than simulation-limited.

Their overall speed could be improved by converting the default renderer to WebGL from Canvas.

**Comment by hunterloftis** [comment]
Possible drop-in solution: https://github.com/gameclosure/webgl-2d

**Comment by hunterloftis** [comment]
Or use Pixi: http://www.goodboydigital.com/pixijs/examples/13/

**Comment by hunterloftis** [comment]
Or take inspiration from this: https://github.com/asalga/XB-PointStream

**Comment by floatdrop** [comment]
I will take Pixi, c'z I used it before.

**Comment by hunterloftis** [comment]
closed by https://github.com/hunterloftis/newton/pull/8
