### ISSUE TITLE
Support removal of bodies and components

### ISSUE THREAD

**Issue by wyattanderson** [hunterloftis/newton#14]
Please forgive me if there's an obvious reason why I shouldn't be doing this, but I'd like to remove things from my simulation periodically beyond just particles. For instance, if I create a body that has associated edges, particles and constraints, I'd like to be able to remove the entire thing from the simulation at a certain point.

I was able to accomplish this for my purposes by adding an `isDestroyed` to `Edge` and adding a `cull` pass into the simulator for the edge list. I can submit a PR with that change if that's valuable.

In general, I'd just like to start a discussion as to the right approach for removal of complex bodies from the simulator.

**Comment by hunterloftis** [comment]
Hi! And definitely, this should be a feature. I would like to in general revisit the destruction/culling of all types - removal needs to be fast but also as automated as possible (without thrashing the GC or leaking memory).

What are your thoughts?
