### ISSUE TITLE
Not in bower registry

### ISSUE THREAD

**Issue by renan** [hunterloftis/newton#5]
On the README you say to download using bower with `bower install newton` however that's not this library.

The `newton` package on bower.io is this one: https://github.com/jpsilvashy/newton

**Comment by hunterloftis** [comment]
Thanks, just updated the readme.

Waiting on bower to update this here: https://github.com/bower/bower/issues/120#issuecomment-26944546

**Comment by floatdrop** [comment]
It's done now.

**Comment by renan** [comment]
Awesome!
