### ISSUE TITLE
Node.js package

### ISSUE THREAD

**Issue by floatdrop** [hunterloftis/newton#7]
I think supporting node `require` will vastly increase audience of newton (aka simple multiplayer game examples).

**Comment by hunterloftis** [comment]
agreed

**Comment by hunterloftis** [comment]
I also want to use node as a standard benchmarking tool that's decoupled from the browser and the renderer.

**Comment by hunterloftis** [comment]
Closed by 14a3fb98c530980392fb6dd7cdfc51928891e746
